### PR TITLE
fix(caching): add surrogate key

### LINKED ISSUE #8: Add surrogate-key response header
In order to be able to invalidate the cache when a github resource has changed, it would be helpful to use a surrogate-key. this is easier than compute all potential external URLs of a static resource.

### Suggestion

- compute the surrogate hash similar to [helix-pipeline](https://github.com/adobe/helix-pipeline/blob/dabab11421d57c1e7f390142cdd7ba3911fe33ec/src/html/set-surrogate-key.js#L29-L32) based on the raw github url of the loaded resource.
- add the surrogate hash to the `Surrogate-Key` response header.

---
- https://github.com/adobe/helix-publish/issues/108
- https://github.com/adobe/helix-pages/issues/17

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #8

### CODE REVIEW

File: test/testStatic.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ describe('Static Delivery Action #integrationtest', () => {
     assert.equal(res.headers['Content-Type'], 'text/css');
     assert.equal(res.headers['X-Static'], 'Raw/Static');
     assert.equal(res.headers['Cache-Control'], 's-maxage=300');
+    assert.equal(res.headers['Surrogate-Key'], 'AYnQlbzbj4dsnOxH');
```
Comment (kptdobe) [inline test/testStatic.js]: I think a fully clean way of testing this would be to mock the `computeSurrogateKey` because if you change its implementation in `helix-shared`, those tests would fail why the code is still correct. 
But I would say it is ok for now ;)

Comment (tripodsan) [reply test/testStatic.js]: > if you change its implementation in `helix-shared`, those tests would fail while the code here is still correct.

well, that's the intention. if the computation is changed, then it's a breaking change. so I need to adjust it here and think of the consequences.

Comment (kptdobe) [reply test/testStatic.js]: Hummm...? The code here is only responsible to output a key in a header. The value inside the key should not matter. If the contract of the `computeSurrogateKey` is to output a hmac hash of the given string, this should be tested in `helix-shared`: you would then detect a breaking change there, not later here...

Comment (tripodsan) [reply test/testStatic.js]: so, assume I don't know about helix-shared. but I base the surrogate logic on the computation of the key. since I also use the helix-shared in my other systems, e.g. in the bot that sends the invalidation request, I need to be able to detect changes when the computation changes. for example, I update helix-shared here (that comes with a different compute) but I don't update it in helix-bot. so I wouldn't realize that it changed.
