### PR TITLE
Fix Static Delivery Failures

### LINKED ISSUE #369: Some static requests fail
```
2020-08-08T15:47:32.256Z: instrumenting epsagon.
2020-08-08T15:47:32.258Z: deliverStatic with adobe/ferrumjsorg/54d751f37633fa777ce0816390b3bdbe515d0295 path=/index.html file=/index.html allow=undefined deny=undefined root= esi=false
2020-08-08T15:47:32.259Z: deliverPlain: url=https://raw.githubusercontent.com/adobe/ferrumjsorg/54d751f37633fa777ce0816390b3bdbe515d0295/undefined.undefined
2020-08-08T15:47:32.438Z: got response. size=14, type=application/octet-stream
2020-08-08T15:47:32.438Z: delivering error undefined 404
```

with versions>1.10.49

### PR DESCRIPTION
**Pull request by trieloff**
Fixes #369 The core fix is here: https://github.com/adobe/helix-static/commit/499ae381a5b5350883df3c90e753846ecc83289f

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -31,8 +31,8 @@ class Router {
     const [route, handler] = pair;
 
     return handler({
-      ...route(path),
       ...options,
+      ...route(path),
```
Comment (stefan-guggisberg) [inline src/router.js:35]: Is this the fix for `.../undefined.undefined` url issue? It's not obvious and I think it would merit inline comments.

Comment (trieloff) [reply src/router.js:39]: done.
